global:
  sandbox_root: /data/yjh/react_inverse_problem_sandboxes
  default_settings:
    model_name: gemini-3-pro-preview
    max_rounds: 10
tasks:
- name: sim
  python_path: /home/yjh/.conda/envs/sim/bin/python
  working_folder: /home/yjh/sim_sandbox/
- name: diff
  python_path: /home/yjh/.conda/envs/ragas/bin/python
  working_folder: /home/yjh/diff_sandbox/
- name: lensless_admm
  python_path: /home/yjh/.conda/envs/lensless/bin/python
  working_folder: /home/yjh/lensless_admm_sandbox/
- name: spectral_ct_examples-master
  python_path: /home/yjh/.conda/envs/spectral_ct/bin/python
  working_folder: /data/yjh/spectral_ct_examples-master_sandbox
- name: storm-analysis-master
  python_path: /data/yjh/storm_env/bin/python
  working_folder: /data/yjh/storm-analysis-master_sandbox
- name: structured-light-python-main
  python_path: /data/yjh/structured_light_env/bin/python
  working_folder: /data/yjh/structured-light-python-main_sandbox
- name: svmbir-master
  python_path: python
  working_folder: /data/yjh/svmbir-master_sandbox
- name: tomopy-master
  python_path: python
  working_folder: /data/yjh/tomopy-master_sandbox
- name: us-beamform-linarray-master
  python_path: /usr/local/anaconda3/bin/python
  working_folder: /data/yjh/us-beamform-linarray-master_sandbox
- name: nirfaster-FF-main_2
  python_path: /usr/local/anaconda3/bin/python
  working_folder: /data/yjh/nirfaster-FF-main_2_sandbox
