global:
  default_settings:
    max_rounds: 10
    model_name: gemini-3-pro-preview
  sandbox_root: /data/yjh/react_inverse_problem_sandboxes
tasks:
- gt_code_path: /home/yjh/sim_sandbox/sim_code.py
  name: sim
  working_folder: /home/yjh/sim_sandbox/
  input_path: '/home/yjh/sim_sandbox/001.tif'
  expected_output_path: '/home/yjh/sim_sandbox/output.tif'
- gt_code_path: /home/yjh/ad_pty/code_2/main.py
  name: ptyrad
  working_folder: /home/yjh/ad_pty/code_2
  input_path: /home/yjh/ad_pty/code_2/sample_data_PrScO3.mat
  expected_output_path: /home/yjh/ad_pty/code_2/output/PSO/20251208_full_N4096_dp256_sparse32_p4_1obj_21slice_dz10_plr1e-4_oalr5e-4_oplr5e-4_slr5e-4_dpblur1_orblur0.4_ozblur1_mamp0.03_4_oathr0.96_oposc_sng1.0_spr0.1/objp_zsum_crop_08bit_iter0020.tif
- gt_code_path: /home/yjh/lfm_sandbox/lfm_code.py
  name: lfm
  working_folder: /home/yjh/lfm_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/oopao_sh_sandbox/main.py
  name: oopao_sh_wfs
  working_folder: /home/yjh/oopao_sh_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/oopao_zernike_sandbox/main.py 
  name: oopao_image_zernike
  working_folder: /home/yjh/oopao_zernike_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/BayHunter_standalone/bayhunter_code.py
  name: bayhunt
  working_folder: /home/yjh/BayHunter_standalone/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/pyeit_sandbox/examples/eit_dynamic_jac3d.py
  name: pyeit
  working_folder: /home/yjh/pyeit_sandbox/examples
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/bpm_sandbox/bpm_code.py
  name: bpm
  working_folder: /home/yjh/bpm_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/diff_sandbox/diff_code.py
  name: diff
  working_folder: /home/yjh/diff_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/insar_sandbox/insar_code.py
  name: insar
  working_folder: /home/yjh/insar_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/pat_sandbox/pat_code.py
  name: pat
  working_folder: /home/yjh/pat_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/lensless_admm_sandbox/lensless_admm_code.py
  name: lensless_admm
  working_folder: /home/yjh/lensless_admm_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/lensless_dl_sandbox/lensless_dl_code.py
  name: lensless_dl
  working_folder: /home/yjh/lensless_dl_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/pnp_cassi_sandbox/pnp_cassi_code.py
  name: pnp_cassi
  working_folder: /home/yjh/pnp_cassi_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/fpm_inr_sandbox/fpm_inr_code.py
  name: fpm_inr
  working_folder: /home/yjh/fpm_inr_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/flfm_sandbox/flfm_code.py
  name: flfm
  working_folder: /home/yjh/flfm_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/lenstronomy_simple_ring_sandbox/main.py
  name: lenstronomy_simple_ring
  working_folder: /home/yjh/lenstronomy_simple_ring_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/lenstronomy_quad_quasar_sandbox/main.py
  name: lenstronomy_quad_quasar
  working_folder: /home/yjh/lenstronomy_quad_quasar_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/lenstronomy_double_quasar_sandbox/main.py
  name: lenstronomy_double_quasar
  working_folder: /home/yjh/lenstronomy_double_quasar_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/lenstronomy_shapelets_sandbox/main.py
  name: lenstronomy_shapelets
  working_folder: /home/yjh/lenstronomy_shapelets_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/lenstronomy_host_decomp_sandbox/main.py
  name: lenstronomy_host_decomp
  working_folder: /home/yjh/lenstronomy_host_decomp_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/dpi_task1_sandbox/dpi_task1.py
  name: dpi_task1
  working_folder: /home/yjh/dpi_task1_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/dpi_task2_sandbox/dpi_task2.py
  name: dpi_task2
  working_folder: /home/yjh/dpi_task2_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /home/yjh/dpi_task3_sandbox/dpi_task3.py
  name: dpi_task3
  working_folder: /home/yjh/dpi_task3_sandbox/
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/AMICO-master_sandbox/amico_code.py
  name: AMICO-master
  working_folder: /data/yjh/AMICO-master_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/carspy-main_sandbox/carspy_code.py
  name: carspy-main
  working_folder: /data/yjh/carspy-main_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/caustics-main_sandbox/caustics_code.py
  name: caustics-main
  working_folder: /data/yjh/caustics-main_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/CT-and-MR-Perfusion-Tool-main_sandbox/ct_mr_perfusion_code.py
  name: CT-and-MR-Perfusion-Tool-main
  working_folder: /data/yjh/CT-and-MR-Perfusion-Tool-main_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/DiffuserCam-Tutorial-master_sandbox/diffuser_cam_code.py
  name: DiffuserCam-Tutorial-master
  working_folder: /data/yjh/DiffuserCam-Tutorial-master_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/dmipy-master_sandbox/dmipy_code.py
  name: dmipy-master
  working_folder: /data/yjh/dmipy-master_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/hcipy-master/hcipy_standalone.py
  name: hcipy-master
  working_folder: /data/yjh/hcipy-master_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/mne-master_sandbox/mne_code.py
  name: mne-master
  working_folder: /data/yjh/mne-master_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/MPIRF-master_sandbox/mpirf_code.py
  name: MPIRF-master
  working_folder: /data/yjh/MPIRF-master_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/MRE-elast-master_sandbox/mre_elast_code.py
  name: MRE-elast-master
  working_folder: /data/yjh/MRE-elast-master_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/mrf-reconstruction-mlmir2020-master_sandbox/mrf_code.py
  name: mrf-reconstruction-mlmir2020-master
  working_folder: /data/yjh/mrf-reconstruction-mlmir2020-master_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/mripy-master_sandbox/mripy_code.py
  name: mripy-master
  working_folder: /data/yjh/mripy-master_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/oct-cbort-main_sandbox/oct_cbort_code.py
  name: oct-cbort-main
  working_folder: /data/yjh/oct-cbort-main_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/phasorpy-main_sandbox/phasorpy_code.py
  name: phasorpy-main
  working_folder: /data/yjh/phasorpy-main_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/PtyLab-main/ptylab_standalone.py
  name: PtyLab-main
  working_folder: /data/yjh/PtyLab-main_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/PyAbel-master_sandbox/pyabel_code.py
  name: PyAbel-master
  working_folder: /data/yjh/PyAbel-master_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/pyDHM-master_sandbox/pydhm_code.py
  name: pyDHM-master
  working_folder: /data/yjh/pyDHM-master_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/PyHoloscope-main_sandbox/pyholoscope_code.py
  name: PyHoloscope-main
  working_folder: /data/yjh/PyHoloscope-main_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/PySMLFM-main_sandbox/pysmlfm_code.py
  name: PySMLFM-main
  working_folder: /data/yjh/PySMLFM-main_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/PyTomography-main/pytomography_standalone.py
  name: PyTomography-main
  working_folder: /data/yjh/PyTomography-main_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/s2ISM-main_sandbox/s2ISM_code.py
  name: s2ISM-main
  working_folder: /data/yjh/s2ISM-main_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/semiblindpsfdeconv-master/semiblind_demo.py
  name: semiblindpsfdeconv-master
  working_folder: /data/yjh/semiblindpsfdeconv-master_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/spectral_ct_examples-master_sandbox/spectral_ct_code.py
  name: spectral_ct_examples-master
  working_folder: /data/yjh/spectral_ct_examples-master_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/storm-analysis-master_sandbox/storm_code.py
  name: storm-analysis-master
  working_folder: /data/yjh/storm-analysis-master_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/structured-light-python-main_sandbox/structured_light_code.py
  name: structured-light-python-main
  working_folder: /data/yjh/structured-light-python-main_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/svmbir-master_sandbox/svmbir_code.py
  name: svmbir-master
  working_folder: /data/yjh/svmbir-master_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/tomopy-master_sandbox/tomopy_code.py
  name: tomopy-master
  working_folder: /data/yjh/tomopy-master_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/us-beamform-linarray-master/us_beamforming.py
  name: us-beamform-linarray-master
  working_folder: /data/yjh/us-beamform-linarray-master_sandbox
  input_path: 
  expected_output_path: 
- gt_code_path: /data/yjh/nirfaster-FF-main_2_sandbox/nirfaster_code.py
  name: nirfaster-FF-main_2
  working_folder: /data/yjh/nirfaster-FF-main_2_sandbox
  input_path: 
  expected_output_path: 
