global:
  default_settings:
    max_rounds: 10
    model_name: gemini-3-pro-preview
  sandbox_root: /data/yjh/react_inverse_problem_sandboxes
tasks:
- expected_output_path: null
  gt_code_path: /data/yjh/structured-light-python-main_sandbox/structured_light_code.py
  input_path: null
  name: structured-light-python-main
  working_folder: /data/yjh/structured-light-python-main_sandbox
- expected_output_path: null
  gt_code_path: /data/yjh/svmbir-master_sandbox/svmbir_code.py
  input_path: null
  name: svmbir-master
  working_folder: /data/yjh/svmbir-master_sandbox
- expected_output_path: null
  gt_code_path: /data/yjh/tomopy-master_sandbox/tomopy_code.py
  input_path: null
  name: tomopy-master
  working_folder: /data/yjh/tomopy-master_sandbox
- expected_output_path: null
  gt_code_path: /data/yjh/us-beamform-linarray-master/us_beamforming.py
  input_path: null
  name: us-beamform-linarray-master
  working_folder: /data/yjh/us-beamform-linarray-master_sandbox
- expected_output_path: null
  gt_code_path: /data/yjh/nirfaster-FF-main_2_sandbox/nirfaster_code.py
  input_path: null
  name: nirfaster-FF-main_2
  working_folder: /data/yjh/nirfaster-FF-main_2_sandbox

- expected_output_path: null
  gt_code_path: /home/yjh/sim_sandbox/sim_code.py
  input_path: null
  name: sim
  working_folder: /home/yjh/sim_sandbox/

- expected_output_path: null
  gt_code_path: /home/yjh/ad_pty/code_2/main.py
  input_path: null
  name: ptyrad
  working_folder: /home/yjh/ad_pty/code_2/

- expected_output_path: null
  gt_code_path: /home/yjh/lfm_sandbox/lfm_code.py
  input_path: null
  name: lfm
  working_folder: /home/yjh/lfm_sandbox/

- expected_output_path: null
  gt_code_path: /home/yjh/lfm_sandbox/lfm_code.py
  input_path: null
  name: lfm
  working_folder: /home/yjh/lfm_sandbox/

- gt_code_path: /home/yjh/oopao_sh_sandbox/main.py
  name: oopao_sh_wfs
  working_folder: /home/yjh/oopao_sh_sandbox/
  input_path: null
  expected_output_path: null
- gt_code_path: /home/yjh/oopao_zernike_sandbox/main.py 
  name: oopao_image_zernike
  working_folder: /home/yjh/oopao_zernike_sandbox/
  input_path: null
  expected_output_path: null
- gt_code_path: /home/yjh/BayHunter_standalone/bayhunter_code.py
  name: bayhunt
  working_folder: /home/yjh/BayHunter_standalone/
  input_path: null
  expected_output_path: null
- gt_code_path: /home/yjh/pyeit_sandbox/examples/eit_dynamic_jac3d.py
  name: pyeit
  working_folder: /home/yjh/pyeit_sandbox/examples
  input_path: null
  expected_output_path: null
- gt_code_path: /home/yjh/bpm_sandbox/bpm_code.py
  name: bpm
  working_folder: /home/yjh/bpm_sandbox/
  input_path: null
  expected_output_path: null
- gt_code_path: /home/yjh/diff_sandbox/diff_code.py
  name: diff
  working_folder: /home/yjh/diff_sandbox/
  input_path: null
  expected_output_path: null
- gt_code_path: /home/yjh/insar_sandbox/insar_code.py
  name: insar
  working_folder: /home/yjh/insar_sandbox/
  input_path: null
  expected_output_path: null
- gt_code_path: /home/yjh/pat_sandbox/pat_code.py
  name: pat
  working_folder: /home/yjh/pat_sandbox/
  input_path: null
  expected_output_path: null
- gt_code_path: /home/yjh/lensless_admm_sandbox/lensless_admm_code.py
  name: lensless_admm
  working_folder: /home/yjh/lensless_admm_sandbox/
  input_path: null
  expected_output_path: null
- gt_code_path: /home/yjh/lensless_dl_sandbox/lensless_dl_code.py
  name: lensless_dl
  working_folder: /home/yjh/lensless_dl_sandbox/
  input_path: null
  expected_output_path: null
